// Fixture data for the browser preview (`bun run preview:ui`). Values mirror
// the macOS defaults in `src-tauri/src/settings.rs` so the preview looks like a
// fresh Mac install unless a scenario parameter says otherwise.

import catalog from "../../../src-tauri/src/catalog/catalog.json";
import type {
  AppSettings,
  AudioDevice,
  HistoryEntry,
  ModelInfo,
  SecureInputStatus,
} from "@/bindings";

const IMPROVE_PROMPT = `<transcript>
\${output}
</transcript>

The above is a transcript generated by a speech-to-text model. Clean it up.
Return only the cleaned text.`;

export const defaultSettings = (): AppSettings => ({
  settings_schema_version: 1,
  bindings: {
    transcribe: {
      id: "transcribe",
      name: "Transcribe",
      description: "Converts your speech into text.",
      default_binding: "option+space",
      current_binding: "option+space",
    },
    transcribe_with_post_process: {
      id: "transcribe_with_post_process",
      name: "Transcribe with Post-Processing",
      description:
        "Converts your speech into text and applies AI post-processing.",
      default_binding: "option+shift+space",
      current_binding: "option+shift+space",
    },
    cancel: {
      id: "cancel",
      name: "Cancel",
      description: "Cancels the current recording.",
      default_binding: "escape",
      current_binding: "escape",
    },
  },
  shortcut_activation: "hold_or_toggle",
  hold_threshold_ms: 300,
  audio_feedback: false,
  audio_feedback_volume: 1.0,
  start_hidden: false,
  autostart_enabled: false,
  selected_model: "",
  onboarding_completed: true,
  always_on_microphone: false,
  selected_microphone: null,
  selected_channel: null,
  clamshell_microphone: null,
  selected_output_device: null,
  selected_language: "auto",
  overlay_position: "bottom",
  debug_mode: false,
  log_level: "debug",
  custom_words: [],
  model_unload_timeout: "min_5",
  word_correction_threshold: 0.18,
  paste_method: "ctrl_v",
  clipboard_handling: "dont_modify",
  auto_submit: false,
  auto_submit_key: "enter",
  post_process_enabled: false,
  post_process_provider_id: "openai",
  post_process_providers: [
    { id: "openai", label: "OpenAI", base_url: "https://api.openai.com/v1" },
    { id: "zai", label: "Z.AI", base_url: "https://api.z.ai/api/paas/v4" },
    {
      id: "openrouter",
      label: "OpenRouter",
      base_url: "https://openrouter.ai/api/v1",
    },
    {
      id: "anthropic",
      label: "Anthropic",
      base_url: "https://api.anthropic.com/v1",
    },
    { id: "groq", label: "Groq", base_url: "https://api.groq.com/openai/v1" },
    {
      id: "custom",
      label: "Custom",
      base_url: "http://localhost:11434/v1",
      allow_base_url_edit: true,
    },
  ],
  post_process_api_keys: {},
  post_process_models: {},
  post_process_prompts: [
    {
      id: "default_improve_transcriptions",
      name: "Improve Transcriptions",
      prompt: IMPROVE_PROMPT,
    },
  ],
  post_process_selected_prompt_id: null,
  mute_while_recording: false,
  append_trailing_space: false,
  app_language: "en",
  experimental_enabled: false,
  lazy_stream_close: false,
  keyboard_implementation: "handy_keys",
  show_tray_icon: true,
  paste_delay_ms: 60,
  paste_delay_after_ms: 60,
  reliable_paste: false,
  typing_tool: "auto",
  external_script_path: null,
  filler_word_removal_enabled: true,
  custom_filler_words: null,
  transcribe_accelerator: "auto",
  ort_accelerator: "auto",
  transcribe_gpu_device: null,
  extra_recording_buffer_ms: 0,
  vad_enabled: true,
  vad_backend: "silero",
  overlay_style: "live",
});

interface CatalogFile {
  filename: string;
  quant: string;
  size_bytes: number;
}

interface CatalogModel {
  id: string;
  revision?: string;
  name: string;
  description: string;
  languages: string[];
  capabilities: {
    streaming: boolean;
    translate: boolean;
    lang_detect: boolean;
  };
  speed_score?: number;
  accuracy_score?: number;
  files: CatalogFile[];
  default_quant?: string;
  recommended?: boolean;
  recommended_rank?: number;
}

// Same mapping as `ModelDescriptor::from` in `src-tauri/src/catalog/mod.rs`.
export const catalogModels = (): ModelInfo[] =>
  (catalog.models as CatalogModel[])
    .map((m) => {
      const file =
        m.files.find((f) => f.quant === m.default_quant) ?? m.files[0];
      return {
        id: `${m.id}/${file.filename}`,
        name: m.name,
        description: m.description,
        filename: file.filename,
        source: {
          HuggingFace: { repo_id: m.id, revision: m.revision ?? "main" },
        },
        size_mb: Math.round(file.size_bytes / 1024 / 1024),
        is_downloaded: false,
        is_downloading: false,
        partial_size: 0,
        is_directory: false,
        engine_type: "TranscribeCpp" as const,
        accuracy_score: (m.accuracy_score ?? 0) / 100,
        speed_score: (m.speed_score ?? 0) / 100,
        supports_translation: m.capabilities.translate,
        is_recommended: m.recommended ?? false,
        supported_languages: m.languages,
        supports_language_selection: m.languages.length > 1,
        is_custom: false,
        supports_streaming: m.capabilities.streaming,
        supports_language_detection: m.capabilities.lang_detect,
        rank: m.recommended_rank ?? Number.MAX_SAFE_INTEGER,
      };
    })
    .sort((a, b) => a.rank - b.rank || a.name.localeCompare(b.name))
    .map(({ rank: _rank, ...model }) => model);

export const microphones: AudioDevice[] = [
  { index: "default", name: "Default", is_default: true },
  { index: "0", name: "MacBook Pro Microphone", is_default: false },
  { index: "1", name: "AirPods Pro", is_default: false },
  { index: "2", name: "Shure MV7", is_default: false },
];

export const outputDevices: AudioDevice[] = [
  { index: "default", name: "Default", is_default: true },
  { index: "0", name: "MacBook Pro Speakers", is_default: false },
  { index: "1", name: "AirPods Pro", is_default: false },
];

const HOUR = 60 * 60;
const now = () => Math.floor(Date.now() / 1000);

export const historyEntries = (): HistoryEntry[] => [
  {
    id: 4,
    timestamp: now() - 120,
    saved: false,
    title: "",
    transcription_text:
      "Remind me to send the quarterly numbers to Ana before Friday.",
    post_processed_text: null,
    post_process_prompt: null,
    post_process_requested: false,
  },
  {
    id: 3,
    timestamp: now() - 3 * HOUR,
    saved: true,
    title: "",
    transcription_text:
      "um so the idea is that we we ship the beta next week and then gather feedback",
    post_processed_text:
      "The idea is that we ship the beta next week and then gather feedback.",
    post_process_prompt: "Improve Transcriptions",
    post_process_requested: true,
  },
  {
    id: 2,
    timestamp: now() - 26 * HOUR,
    saved: false,
    title: "",
    transcription_text:
      "This is a much longer dictation to check how the history list handles text that wraps over several lines. It keeps going so the card has to grow, and it should still be easy to scan, copy, and delete without the layout breaking apart.",
    post_processed_text: null,
    post_process_prompt: null,
    post_process_requested: false,
  },
  {
    id: 1,
    timestamp: now() - 8 * 24 * HOUR,
    saved: false,
    title: "",
    transcription_text: "Hello world.",
    post_processed_text: null,
    post_process_prompt: null,
    post_process_requested: false,
  },
];

export const secureInput = (active: boolean): SecureInputStatus => ({
  enabled: active,
  sustained: active,
  culprit_pid: active ? 4242 : null,
  culprit_name: active ? "1Password" : null,
  fallback_active: false,
  covered_bindings: [],
  degraded_bindings: [],
  uncovered_bindings: active ? ["transcribe"] : [],
  recorder_blocked: false,
});

export const LIVE_TEXT = {
  committed: "So the plan for next week is to finish the redesign of the",
  tentative: "settings window",
};
